In [1]:
import numpy as np

In [11]:
#numpy array create from array

arr = np.array([1,2,3,4,5,6])
print(arr, type(arr), arr.dtype, arr.shape)

arr1 = np.array([1,2,3,4,5,6,"nahin"])
print(arr1, type(arr1), arr1.dtype, arr1.shape)

arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (arr2D, arr2D.shape)

[1 2 3 4 5 6] <class 'numpy.ndarray'> int64 (6,)
['1' '2' '3' '4' '5' '6' 'nahin'] <class 'numpy.ndarray'> <U21 (7,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [34]:
#create array

arr1 = np.zeros((3, 3), dtype = "int64")
print (arr1, arr1.shape)

arr2 = np.ones((5), dtype = "int64")
print (arr2, arr2.shape)

arr3 = np.full((3, 4), 100, dtype = "int64")
print (arr3, arr3.shape)

arr4 = np.eye((3), dtype = "int64")
print (arr4, arr4.shape)

arr5 = np.arange(1, 11, 2)
print (arr5, arr5.shape)

arr6 = np.linspace(1, 100, 3)
print (arr6, arr6.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]] (3, 3)
[1 1 1 1 1] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[1 3 5 7 9] (5,)
[  1.   50.5 100. ] (3,)


In [36]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print (arr.shape)
print (arr.size)
print (arr.dtype)
print (arr.ndim)

float_arr = arr.astype(np.float64)
print (float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [39]:
arr = np.array([[1,2,3],[4,5,6]])
print (arr, arr.shape)

change_shape = arr.reshape(3,2)
print (change_shape, change_shape.shape)

flt = arr.flatten()
print(flt, flt.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [41]:
# copy vs view
#python list
py_list = [1,2,3,4,5,6]
sub_list = py_list[1:3]
sub_list[0] = 200
print (sub_list)
print (py_list)

#numpy arr
arr = np.array(py_list)
sub_arr = arr[1:3]
sub_arr[0] = 200
print (sub_arr)
print (arr)

[200, 3]
[1, 2, 3, 4, 5, 6]
[200   3]
[  1 200   3   4   5   6]
