In [2]:
import numpy as np

In [3]:
#numpy array create from array

arr = np.array([1,2,3,4,5,6])
print(arr, type(arr), arr.dtype, arr.shape)

arr1 = np.array([1,2,3,4,5,6,"nahin"])
print(arr1, type(arr1), arr1.dtype, arr1.shape)

arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (arr2D, arr2D.shape)

[1 2 3 4 5 6] <class 'numpy.ndarray'> int64 (6,)
['1' '2' '3' '4' '5' '6' 'nahin'] <class 'numpy.ndarray'> <U21 (7,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [4]:
#create array

arr1 = np.zeros((3, 3), dtype = "int64")
print (arr1, arr1.shape)

arr2 = np.ones((5), dtype = "int64")
print (arr2, arr2.shape)

arr3 = np.full((3, 4), 100, dtype = "int64")
print (arr3, arr3.shape)

arr4 = np.eye((3), dtype = "int64")
print (arr4, arr4.shape)

arr5 = np.arange(1, 11, 2)
print (arr5, arr5.shape)

arr6 = np.linspace(1, 100, 3)
print (arr6, arr6.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]] (3, 3)
[1 1 1 1 1] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[1 3 5 7 9] (5,)
[  1.   50.5 100. ] (3,)


In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print (arr.shape)
print (arr.size)
print (arr.dtype)
print (arr.ndim)

float_arr = arr.astype(np.float64)
print (float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print (arr, arr.shape)

change_shape = arr.reshape(3,2)
print (change_shape, change_shape.shape)

flt = arr.flatten()
print(flt, flt.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [7]:
# copy vs view
#python list
py_list = [1,2,3,4,5,6]
sub_list = py_list[1:3]
sub_list[0] = 200
print (sub_list)
print (py_list)

#numpy arr
arr = np.array(py_list)
sub_arr = arr[1:3]
sub_arr[0] = 200
print (sub_arr)
print (arr)

[200, 3]
[1, 2, 3, 4, 5, 6]
[200   3]
[  1 200   3   4   5   6]


In [12]:
# multi-dimensional array

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])

print (arr2D)
print(np.sum(arr2D))

sum_of_colum = np.sum(arr2D, axis = 0)
print (sum_of_colum)

sum_of_raw = np.sum(arr2D, axis = 1)
print (sum_of_raw)

print (arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [17]:
#3D array

arr3D = np.array([[[1,2],[3,4],[5,6]], [[7,8],[9,10],[11,12]]])

print (arr3D, arr3D.shape)
print (arr3D[0,1,1])
print(arr3D[:, 0, :])
arr3D[:, 0, :] = 99
print (arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[1 2]
 [7 8]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [20]:
#normalization

arr = np.array([[1,2], [3,4]])

mean = (np.mean(arr))
std =  (np.std(arr))
print ((arr - mean)/std)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [31]:
#math function

# aggregate

arr = np.array ([1,2,3,4,5])

print (np.sum(arr))
print (np.prod(arr))
print (np.min(arr))
print (np.argmin(arr))
print (np.max(arr))
print (np.argmax(arr))
print (np.mean(arr))
print (np.median(arr))
print (np.std(arr))
print (np.var(arr))

15
120
1
0
5
4
3.0
3.0
1.4142135623730951
2.0


In [36]:
#power function

arr = np.array ([1,2,3,4,5])

print (np.square(arr))
print (np.sqrt(arr))

print (np.pow(arr, 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [38]:
#log

arr = np.array ([1,2,3,4,5])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [41]:
#rounding 
print(np.round(3.95))
print(np.ceil(3.95))
print(np.floor(3.95))
print(np.trunc(3.95))

4.0
4.0
3.0
3.0


In [43]:
arr = np.array ([1,2,3,4,5,5,3,2,8,9,-2,-3])

print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

[-3 -2  1  2  3  4  5  8  9]
[-3 -2  1  2  2  3  3  4  5  5  8  9]
[1 2 3 4 5 5 3 2 8 9 2 3]
